### ISSUE TITLE
ValueError: not enough values to unpack (expected 2, got 1)

### ISSUE THREAD

**Issue by dreamflasher** [oxhacks/onestandard#1]
When executing I get the following error:

```
Traceback (most recent call last):
  File "/root/git/onestandard/process_notes.py", line 19, in <module>
    for title, headers, content in notes:
  File "/root/git/onestandard/onestandard/processor.py", line 64, in get_notes
    title, headers, content = extract_parts(note)
  File "/root/git/onestandard/onestandard/processor.py", line 46, in extract_parts
    title, headers = parts[:2]
ValueError: not enough values to unpack (expected 2, got 1)
```

**Comment by intrepidsilence** [comment]
I get the same thing, but one fewer values getting passed:

Traceback (most recent call last):
  File "process_notes.py", line 19, in <module>
    for title, headers, content in notes:
  File "/xxxx/xxxx/onestandard/processor.py", line 64, in get_notes
    title, headers, content = extract_parts(note)
  File "xxxx/xxxx/onestandard/onestandard/processor.py", line 46, in extract_parts
    title, headers = parts[:2]
ValueError: not enough values to unpack (expected 2, got 0)

**Comment by bmhj2** [comment]
Same issue here - would love to know what was causing this.

`Traceback (most recent call last):
  File "process_notes.py", line 19, in <module>
    for title, headers, content in notes:
  File "/mnt/Behemoth/onestandard-master/onestandard/processor.py", line 64, in get_notes
    title, headers, content = extract_parts(note)
  File "/mnt/Behemoth/onestandard-master/onestandard/processor.py", line 46, in extract_parts
    title, headers = parts[:2]
ValueError: not enough values to unpack (expected 2, got 1)
`

**Comment by oxhacks** [comment]
Hey there - thanks for using the library! I hadn't looked at this in a while, but I just pushed a fix in 15d18e2 that should wrap that error and keep going if it can't parse the line. If you can share some non-sensitive examples I'd be happy to fix it for "real".

**Comment by bmhj2** [comment]
Many apologies - I missed this message completely. Will have another go at this and post something more substantive if I can't make it work another time.

**Comment by bmhj2** [comment]
Hi again. OK - I've attached a non-sensitive [example](https://github.com/oxhacks/onestandard/files/7610883/example.txt) of some notes from academic reading, to show the output. I'm not sure whether this belongs under the same issue as before, since I'm very new to this, but as far as I can tell it is now parsing the .mht files fairly successfully and producing JSON notation that Standard Notes can make sense of. But the line breaks are not coming out very well - as you'll see from this file, it's preserving \n and similar escaped markers throughout, and that makes the text quite hard to read. It's usable, but it's not quite ideal.

Can anything be done:

1. to improve the rendering of the line breaks when OneStandard spits all this out, so that it imports into SN with line breaks intact?
2. [separately and definitely not connected with the original request] to make different pages from OneNote appear as separate markdown files/notes in SN?

Any pointers here much appreciated, including sending me off to a better source of advice/guidance if appropriate.
